<!-- Tab Update -->
<div class="tab-pane fade" id="nav-update" role="tabpanel" aria-labelledby="nav-update-tab">
    <div id="update-inputs-container" class="row m-0 w-100 justify-content-center">
        <div class="col-12 col-md-4"><div class="row w-100 p-0 m-0"><div class="input-container col-12 d-flex" title="ID"><label for="departmentname" class="input-title align-self-center">ID Departamento</label><p class="input-value align-self-center" id="update-department-uid"></p></div><div class="input-container col-12 d-flex" title="Nombre"><label for="update-department-name" class="input-title align-self-center">Nombre</label><input type="text" autofocus id="update-department-name" class="input-value form-control align-self-center" name="name" placeholder="Tecnología"></div><div class="input-container col-12 d-flex" title="Presupuesto Mensual"><label for="department-budget" class="input-title align-self-center">Presupuesto Mensual</label><input type="number" autofocus id="update-department-budget" class="input-value form-control align-self-center" name="budget" placeholder="$80.000.000"></div></div></div>
        <div class="col-12 col-md-4"><div class="row w-100 p-0 m-0"><div class="input-container col-12 d-flex" title="Número de empleados"><label for="department-employees" class="input-title align-self-center">Número de empleados</label><p class="input-value align-self-center" id="update-department-employees"></p></div><div class="input-container col-12 d-flex" title="Director"><label for="department-director" class="input-title align-self-center">Director</label><select class="input-value form-select align-self-center" id="update-department-director" aria-label="Default select example"></select></div><div class="input-container col-12 d-flex" title="Presupuesto Utilizado"><label for="department-budget-used" class="input-title align-self-center">Presupuesto Utilizado</label><p class="input-value align-self-center" id="update-department-budget-used">0</p></div></div></div>
        <div class="col-12 col-md-4 d-flex flex-column justify-content-center"><div class="d-flex justify-content-center" id="balance-button"><i class="fa-solid fa-scale-balanced"></i><p class="align-self-center">Balance</p></div><div class="d-block" id="department-sub-opt-container"><div class="d-flex justify-content-between"><div class="align-self-center" id="update-department-go-traceability"><i class="fa-solid fa-bars-progress"></i></div><div class="align-self-center" id="update-department-delete"><i class="fa-solid fa-trash-can"></i></div><div class="align-self-center d-none" id="update-department-restore"><i class="fa-solid fa-lightbulb"></i></div></div></div></div>
    </div>
    <button class="btn btn-secondary" id="update-department-button">Actualizar</button>
    <nav><div class="nav nav-tabs sub-nav-tabs" id="sub-nav-tab" role="tablist"><button class="nav-link active" id="sub-nav-employee-tab" data-bs-toggle="tab" data-bs-target="#sub-nav-employee" type="button" role="tab" aria-controls="sub-nav-employee" aria-selected="true">Empleados</button></div></nav>
    <div class="tab-content" id="sub-nav-tabContent">@include('erp.departments.employee')</div>
</div>