export const incomeState = {
    tabsView: {
        'nav-list-tab': false,
        'nav-create-tab': false,
        'nav-traceability-tab': false,
        'nav-update-tab': false,
    },
    currentTab: null,
    currentContainer: null,
    incomes: [],
    currentIncome: null,
    incomeId: null,
    incomeStatesTotals: {
        '-1': {total: 0, text: 'Todas', class: 'state-1'},
        '0': {total: 0, text: 'Pendiente', class: 'state-0'},
        '1': {total: 0, text: 'Rechazada', class: 'state-1'},
        '2': {total: 0, text: 'Aprobada', class: 'state-2'},
        '3': {total: 0, text: 'Pagada', class: 'state-3'},
        '4': {total: 0, text: 'Facturada', class: 'state-4'},
    },
    pagination: {page: 1, per_page: 10, total: 0},
    clientsList: [],
    currentClient: null,
    selectedLicense: [],
    currentLicencesList: [],
    createCurrentLicenses: [],
    receiversList: [],
    currentAdvanceIncome: null,
    advancesList: [],
    currentAdvance: null,
};