export const contractState = {
    tabsView: {
        'nav-list-tab': false,
        'nav-create-tab': false,
        'nav-types-tab': false,
        'nav-templates-tab': false,
        'nav-update-tab': false,
    },
    contracts: [],
    currentContract: null,
    catalogs: {
        clients: [],
        employees: [],
        providers: [],
        licenses: [],
        types: [],
        templates: [],
        variables: [],
    },
    editingTypeId: null,
    editingTemplateId: null,
    sendingContractIds: {},
    currentTab: null,
    urlContractId: null,
    dbPagination: {
        page: 1,
        per_page: 10,
        total: 0,
        totalPages: 0,
    },
};