<div class="tab-pane fade contracts-pane" id="nav-schedules" role="tabpanel" aria-labelledby="nav-schedules-tab">
    <div class="contracts-form-section contracts-schedule-form">
        <h3 id="contract-schedule-form-title">Nueva programación</h3>
        <div class="contracts-form-grid">
            <div><div class="input-container d-flex"><label for="contract-schedule-name" class="input-title align-self-center">Nombre</label><input type="text" id="contract-schedule-name" class="form-control input-value" placeholder="Contratos mensuales de clientes"></div><div class="input-container d-flex"><label for="contract-schedule-type" class="input-title align-self-center">Tipo</label><select id="contract-schedule-type" class="form-select input-value contract-type-select"></select></div><div class="input-container d-flex"><label for="contract-schedule-template" class="input-title align-self-center">Plantilla</label><select id="contract-schedule-template" class="form-select input-value"></select></div></div>
            <div><div class="input-container d-flex"><label for="contract-schedule-target-type" class="input-title align-self-center">Fuente</label><select id="contract-schedule-target-type" class="form-select input-value"></select></div><div class="input-container d-flex"><label for="contract-schedule-target-id" class="input-title align-self-center">Titular</label><select id="contract-schedule-target-id" class="form-select input-value"></select></div><p class="contracts-help">Deja Titular en "Todos" para crear un contrato para cada registro activo de la fuente.</p></div>
        </div>
        <div class="contracts-form-grid"><div><div class="input-container d-flex"><label for="contract-schedule-frequency" class="input-title align-self-center">Frecuencia</label><select id="contract-schedule-frequency" class="form-select input-value"><option value="daily">Diaria</option><option value="weekly">Semanal</option><option value="monthly" selected>Mensual</option><option value="yearly">Anual</option></select></div><div class="input-container d-flex"><label for="contract-schedule-interval" class="input-title align-self-center">Cada</label><input type="number" min="1" id="contract-schedule-interval" class="form-control input-value" value="1"></div></div><div><div class="input-container d-flex"><label for="contract-schedule-next-run" class="input-title align-self-center">Próxima ejecución</label><input type="datetime-local" id="contract-schedule-next-run" class="form-control input-value"></div><div class="input-container d-flex"><label for="contract-schedule-ends" class="input-title align-self-center">Finaliza</label><input type="datetime-local" id="contract-schedule-ends" class="form-control input-value"></div></div></div>
        <div class="contracts-inline-form mt-3"><label class="form-check-label"><input type="checkbox" id="contract-schedule-send" class="form-check-input" checked> Enviar automáticamente</label><label class="form-check-label"><input type="checkbox" id="contract-schedule-active" class="form-check-input" checked> Activa</label><button class="btn btn-secondary" id="contract-schedule-save"><i class="fa-solid fa-plus"></i> Agregar</button><button class="btn btn-link d-none" id="contract-schedule-cancel">Cancelar</button></div>
    </div>
    <div class="table-responsive"><table id="contract-schedules-table" class="table table-hover table-sm align-middle"><thead><tr><th>Nombre</th><th>Tipo</th><th>Fuente</th><th>Próxima ejecución</th><th>Envío</th><th>Estado</th><th>Acciones</th></tr></thead><tbody id="contract-schedules-table-body"></tbody></table></div>
</div>