<div class="tab-pane fade" id="sub-nav-hiring" role="tabpanel" aria-labelledby="sub-nav-hiring-tab">
    <div id="create-employee-inputs-container" class="row w-100">
        <div class="col-12 col-md-4">
            <div class="row w-100 p-0 m-0">
                <div class="input-container col-12 d-flex" title="Fecha de ingreso"><label for="employeename" class="input-title align-self-center">Ingreso</label><input type="date" id="hiring-employee-entry-date" class="input-value form-control align-self-center" name="entry_date" placeholder="Juan"></div>
                <div class="input-container col-12 d-flex" title="Tipo de pago"><label for="employeename" class="input-title align-self-center">Tipo de pago</label><select class="form-select input-value align-self-center" id="hiring-employee-payment-type" name="payment-type"><option value="0" selected>Quincenal</option><option value="1">Mensual</option><option value="2">Semanal</option><option value="3">Diario</option></select></div>
                <div class="input-container col-12 d-flex" title="Banco"><label for="employeename" class="input-title align-self-center">Banco</label><input type="text" id="hiring-employee-bank" class="input-value form-control align-self-center" name="bank" placeholder="Bancolombia"></div>
                <div class="input-container col-12 d-flex" title="Cuenta"><label for="employeename" class="input-title align-self-center">Cuenta</label><input type="text" id="hiring-employee-account-number" class="input-value form-control align-self-center" name="account-number" placeholder="1234567890"></div>
                <div class="input-container col-12 d-flex" title="Tipo de cuenta"><label for="employeename" class="input-title align-self-center">Tipo de cuenta</label><select class="form-select input-value align-self-center" id="hiring-employee-account-type" name="account-type"><option value="0" selected>Ahorros</option><option value="1">Corriente</option></select></div>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="input-container col-12 d-flex" title="Salario"><label for="employeename" class="input-title align-self-center">Salario</label><input type="number" id="hiring-employee-salary" class="input-value form-control align-self-center" name="salary" placeholder="1234567890"></div>
            <div class="input-container col-12 d-flex" title="Contrato"><label for="employeename" class="input-title align-self-center">Contrato</label><input type="text" id="hiring-employee-contract" class="input-value form-control align-self-center" name="contract" placeholder="1234567890"></div>
            <div class="input-container col-12 d-flex" title="Departamento"><label for="employeename" class="input-title align-self-center">Departamento</label><select class="form-select input-value align-self-center" id="hiring-employee-department" name="department"></select></div>
            <div class="input-container col-12 d-flex" title="Cargo"><label for="employeename" class="input-title align-self-center">Cargo</label><input type="text" id="hiring-employee-charge" class="input-value form-control align-self-center" name="charge" placeholder="Ejecutivo de cuenta"></div>
        </div>
        <div class="col-12 col-md-4">
            <div class="input-container col-12 d-flex" title="EPS"><label for="employeename" class="input-title align-self-center">EPS</label><div class="crud-input-container input-value" prefix="/admin/eps/"><div class="crud-input-selected-container d-flex justify-content-between" id="hiring-employee-eps"><input type="text" class="crud-current-selected-input align-self-center" placeholder="Colsubsidio"><i class="crud-input-arrow fa-solid fa-chevron-down align-self-center"></i></div><ul class="crud-list closed scrollable"><li class="crud-item-add d-flex justify-content-between"><input type="text" class="crud-item-add-input align-self-center" placeholder="Agregar"><i class="crud-item-add-icon fa-solid fa-plus align-self-center"></i></li></ul></div></div>
            <div class="input-container col-12 d-flex" title="AFP"><label for="employeename" class="input-title align-self-center">AFP</label><div class="crud-input-container input-value" prefix="/admin/afp/"><div class="crud-input-selected-container d-flex justify-content-between" id="hiring-employee-afp"><input type="text" class="crud-current-selected-input align-self-center" placeholder="Compensar"><i class="crud-input-arrow fa-solid fa-chevron-down align-self-center"></i></div><ul class="crud-list closed scrollable"><li class="crud-item-add d-flex justify-content-between"><input type="text" class="crud-item-add-input align-self-center" placeholder="Agregar"><i class="crud-item-add-icon fa-solid fa-plus align-self-center"></i></li></ul></div></div>
            <div class="input-container col-12 d-flex" title="ARL"><label for="employeename" class="input-title align-self-center">ARL</label><div class="crud-input-container input-value" prefix="/admin/arl/"><div class="crud-input-selected-container d-flex justify-content-between" id="hiring-employee-arl"><input type="text" class="crud-current-selected-input align-self-center" placeholder="Coosalud"><i class="crud-input-arrow fa-solid fa-chevron-down align-self-center"></i></div><ul class="crud-list closed scrollable"><li class="crud-item-add d-flex justify-content-between"><input type="text" class="crud-item-add-input align-self-center" placeholder="Agregar"><i class="crud-item-add-icon fa-solid fa-plus align-self-center"></i></li></ul></div></div>
            <div class="input-container col-12 d-flex" title="Salida"><label for="employeename" class="input-title align-self-center">Salida</label><input type="date" id="hiring-employee-retirement-date" class="input-value form-control align-self-center" name="retirement_date" placeholder="Juan"></div>
        </div>
        <button class="btn btn-secondary align-self-center" id="update-employee-hiring-button"><i class="fa-solid fa-file-invoice"></i></button>
    </div>
</div>