<!-- Tab Update -->
<div class="tab-pane fade" id="nav-update" role="tabpanel" aria-labelledby="nav-update-tab">
    <nav><div class="nav nav-tabs sub-nav-tabs" id="sub-nav-tab" role="tablist"><button class="nav-link active" id="sub-nav-general-tab" data-bs-toggle="tab" data-bs-target="#sub-nav-general" type="button" role="tab" aria-controls="sub-nav-general" aria-selected="true">General</button><button class="nav-link" id="sub-nav-hiring-tab" data-bs-toggle="tab" data-bs-target="#sub-nav-hiring" type="button" role="tab" aria-controls="sub-nav-hiring" aria-selected="false">Contratación</button><button class="nav-link" id="sub-nav-documents-tab" data-bs-toggle="tab" data-bs-target="#sub-nav-documents" type="button" role="tab" aria-controls="sub-nav-documents" aria-selected="false">Documentos</button><button class="nav-link" id="sub-nav-licenses-tab" data-bs-toggle="tab" data-bs-target="#sub-nav-licenses" type="button" role="tab" aria-controls="sub-nav-licenses" aria-selected="false">Licencias</button></div></nav>
    <div class="tab-content" id="sub-nav-tabContent">
        <div class="tab-pane fade show active" id="sub-nav-general" role="tabpanel" aria-labelledby="sub-nav-general-tab">
    <div id="update-inputs-container" class="row m-0 w-100 justify-content-center">
        <div class="col-12 d-flex flex-column justify-content-center" id="header-container"><div class="row justify-content-center"><div class="col-12"><div class="d-flex justify-content-center"><div class="multimedia-input-container"><div id="update-employee-img-container" class="image-container d-flex justify-content-center"><input type="file" name="photo" id="update-employee-img" class="d-none input_image" accept="image/*"><i class="fa-regular fa-image align-self-center image-icon"></i></div><i class="fa-solid fa-plus image-plus-icon"></i></div></div></div></div></div>
        <div class="col-12 col-md-4"><div class="row w-100 p-0 m-0">
            <div class="input-container col-12 d-flex" title="ID"><label for="employeename" class="input-title align-self-center">ID Empleado</label><p class="input-value align-self-center" id="update-employee-uid"></p></div>
            <div class="input-container col-12 d-flex" title="Nombre"><label for="update-employee-name" class="input-title align-self-center">Nombre/s</label><input type="text" autofocus id="update-employee-name" class="input-value form-control align-self-center" name="name" placeholder="Juan"></div>
            <div class="input-container col-12 d-flex" title="Apellidos"><label for="employee-last-name" class="input-title align-self-center">Apellido/s</label><input type="text" autofocus id="update-employee-last-name" class="input-value form-control align-self-center" name="last-name" placeholder="Posada"></div>
            <div class="input-container col-12 d-flex" title="Tipo de ID"><label for="update-employee-id-type" class="input-title align-self-center">Tipo ID</label><select class="form-select input-value align-self-center" id="update-employee-id-type" name="id-type"><option value="0" selected>Nit</option><option value="1">Cédula</option><option value="2">Pasaporte</option><option value="3">Cédula extranjera</option></select></div>
            <div class="input-container col-12 d-flex" title="Identificación"><label for="update-employee-identification" class="input-title align-self-center">Identificación</label><input type="text" id="update-employee-identification" class="input-value form-control align-self-center" name="identification" placeholder="1234567890"></div>
        </div></div>
        <div class="col-12 col-md-4"><div class="row w-100 p-0 m-0">
            <div class="input-container col-12 d-flex" title="Estado"><label for="update-employee-state" class="input-title align-self-center">Estado</label><div class="toggle-container row" value="1" id="update-employee-state"><div class="toggle-value d-flex justify-content-center col-6" value="1"><p>Activo</p></div><div class="toggle-value d-flex justify-content-center col-6" value="0"><p>Inactivo</p></div></div></div>
            <div class="input-container col-12 d-flex" title="País"><label for="update-employee-country" class="input-title align-self-center">País</label><div class="crud-input-container input-value" prefix="/admin/country/"><div class="crud-input-selected-container d-flex justify-content-between" id="update-employee-country"><input type="text" class="crud-current-selected-input align-self-center" placeholder="Colombia"><i class="crud-input-arrow fa-solid fa-chevron-down align-self-center"></i></div><ul class="crud-list closed scrollable"><li class="crud-item-add d-flex justify-content-between"><input type="text" class="crud-item-add-input align-self-center" placeholder="Agregar"><i class="crud-item-add-icon fa-solid fa-plus align-self-center"></i></li></ul></div></div>
            <div class="input-container col-12 d-flex" title="Contraseña"><label for="update-employee-phone" class="input-title align-self-center">Teléfono</label><input type="number" id="update-employee-phone" class="input-phone input-value form-control align-self-center" name="phone" placeholder="3002583697"></div>
            <div class="input-container col-12 d-flex"><label for="employeename" class="input-title align-self-center">Correo P.</label><input type="email" id="update-employee-personal-email" class="input-personal-email input-value form-control align-self-center" name="personal-email" placeholder="juanp@gmail.com"></div>
            <div class="input-container col-12 d-flex"><label for="employeename" class="input-title align-self-center">Correo E.</label><input type="email" id="update-employee-work-email" class="input-work-email input-value form-control align-self-center" name="work-email" placeholder="juanp@opzio.co"></div>
        </div></div>
        <div class="col-12 col-md-4 d-flex flex-column justify-content-center"><div class="d-flex justify-content-center" id="balance-button"><i class="fa-solid fa-scale-balanced"></i><p class="align-self-center">Balance</p></div><div class="d-block" id="employee-sub-opt-container"><div class="d-flex justify-content-between"><div class="align-self-center" id="update-employee-go-traceability"><i class="fa-solid fa-bars-progress"></i></div><div class="align-self-center" id="update-employee-delete"><i class="fa-solid fa-ban"></i></div><div class="align-self-center d-none" id="update-employee-restore"><i class="fa-solid fa-lightbulb"></i></div></div></div></div>
    </div>
    <button class="btn btn-secondary" id="update-employee-button">Actualizar</button>
        </div>
        @include('erp.employees.hiring')
        @include('erp.employees.documents')
        @include('erp.employees.licenses')
    </div>
</div>