<!-- Tab Update -->
<div class="tab-pane fade" id="nav-update" role="tabpanel" aria-labelledby="nav-update-tab">
    <div id="update-inputs-container" class="row m-0 p-0 w-100">
        <div class="col-12 d-flex flex-column justify-content-center" id="header-container"><div class="row d-flex justify-content-center"><div class="col-3 col-md-4 align-self-center"><div class="d-flex justify-content-center"><div class="multimedia-input-container"><div id="update-provider-img-container" class="image-container d-flex justify-content-center"><input type="file" name="photo" id="update-provider-img" class="d-none input_image" accept="image/*"><i class="fa-regular fa-image align-self-center image-icon"></i></div><i class="fa-solid fa-plus image-plus-icon"></i></div></div></div><div class="col-9 col-md-5 align-self-center"><div class="row"><div class="input-container col-12 d-flex" title="Apellido/s del usuario"><label for="providername" class="input-title align-self-center">ID Proveedor</label><p id="update-provider-unique-id" class="m-0 p-0 align-self-center"></p></div><div class="input-container col-12 d-flex" title="ID del usuario"><label for="providername" class="input-title align-self-center">Estado</label><div class="toggle-container row" value="1" id="update-provider-state"><div class="toggle-value d-flex justify-content-center col-6" value="1"><p>Activo</p></div><div class="toggle-value d-flex justify-content-center col-6" value="0"><p>Inactivo</p></div></div></div></div></div><div class="col-3 align-self-center"><div class="d-block" id="provider-sub-opt-container"><div class="d-flex justify-content-center"><div class="align-self-center" id="update-provider-go-traceability"><i class="fa-solid fa-bars-progress"></i></div><div class="align-self-center" id="update-provider-delete"><i class="fa-solid fa-trash-can"></i></div><div class="align-self-center" id="update-provider-restore"><i class="fa-solid fa-lightbulb"></i></div></div></div></div></div></div>
        <div class="col-12 col-md-4"><div class="row w-100 p-0 m-0"><div class="input-container col-12 d-flex" title="ID del usuario"><label for="providername" class="input-title align-self-center">Proveedor</label><input type="text" autofocus id="update-provider-name" class="input-value form-control align-self-center" name="name" placeholder="Empresa / Nombre y apellido"></div><div class="input-container col-12 d-flex" title="Identificación del usuario"><label for="providername" class="input-title align-self-center">Tipo ID</label><select class="form-select input-value align-self-center" id="update-provider-id-type" name="identification_type"><option value="0" selected>Nit</option><option value="1">Cédula</option><option value="2">Pasaporte</option><option value="3">Cédula extranjera</option></select></div><div class="input-container col-12 d-flex" title="Apellido/s del usuario"><label for="providername" class="input-title align-self-center">Identificación</label><input type="text" id="update-provider-identification" class="input-value form-control align-self-center" name="identification" placeholder="1234567890"></div><div class="input-container col-12 d-flex" title="País"><label for="countries" class="input-title align-self-center">País</label><div class="crud-input-container input-value" prefix="/admin/country/"><div class="crud-input-selected-container d-flex justify-content-between" id="update-provider-country"><input type="text" class="crud-current-selected-input align-self-center" placeholder="Colombia"><i class="crud-input-arrow fa-solid fa-chevron-down align-self-center"></i></div><ul class="crud-list closed scrollable"><li class="crud-item-add d-flex justify-content-between"><input type="text" class="crud-item-add-input align-self-center" placeholder="Agregar"><i class="crud-item-add-icon fa-solid fa-plus align-self-center"></i></li></ul></div></div></div></div>
        <div class="col-12 col-md-4"><div class="row w-100 p-0 m-0"><div class="input-container col-12 d-flex" title="Correo del usuario"><label for="providername" class="input-title align-self-center">Dirección</label><input type="text" id="update-provider-address" class="input-value form-control align-self-center" name="address" placeholder="cll 8 # 32 - 52"></div><div class="input-container col-12 d-flex" title="Correo del usuario"><label for="providername" class="input-title align-self-center">Teléfono</label><input type="number" id="update-provider-phone" class="input-value form-control align-self-center" name="phone" placeholder="3002583697"></div><div class="input-container col-12 d-flex" title="Contraseña del usuario"><label for="providername" class="input-title align-self-center">Correo</label><input type="email" id="update-provider-email" class="input-email input-value form-control align-self-center" name="email" placeholder="google@gmail.com"></div><div class="input-container col-12 d-flex"><label for="providername" class="input-title align-self-center">Sector</label><div class="crud-input-container input-value" prefix="/admin/sector/"><div class="crud-input-selected-container d-flex justify-content-between" id="update-provider-sector"><input type="text" class="crud-current-selected-input align-self-center" placeholder="Servicios Financieros"><i class="crud-input-arrow fa-solid fa-chevron-down align-self-center"></i></div><ul class="crud-list closed scrollable"><li class="crud-item-add d-flex justify-content-between"><input type="text" class="crud-item-add-input align-self-center" placeholder="Agregar"><i class="crud-item-add-icon fa-solid fa-plus align-self-center"></i></li></ul></div></div></div></div>
        <div class="col-12 col-md-4"><div class="input-container col-12"><label for="providername" class="input-title align-self-center d-block">Descripción</label><textarea id="update-provider-description" name="description" rows="5" placeholder="Breve descripción de la empresa o providere."></textarea></div></div>
    </div>
    <button class="btn btn-secondary" id="update-provider-button">Actualizar</button>
    <nav><div class="nav nav-tabs sub-nav-tabs" id="sub-nav-tab" role="tablist"><button class="nav-link" id="sub-nav-payments-tab" data-bs-toggle="tab" data-bs-target="#sub-nav-payments" type="button" role="tab" aria-controls="sub-nav-payments" aria-selected="true">Pagos</button><button class="nav-link active" id="sub-nav-documents-tab" data-bs-toggle="tab" data-bs-target="#sub-nav-documents" type="button" role="tab" aria-controls="sub-nav-documents" aria-selected="true">Documentos</button><button class="nav-link" id="sub-nav-contacts-tab" data-bs-toggle="tab" data-bs-target="#sub-nav-contacts" type="button" role="tab" aria-controls="sub-nav-contacts" aria-selected="true">Contactos</button></div></nav>
    <div class="tab-content" id="sub-nav-tabContent">
        @include('erp.providers.payments')
        @include('erp.providers.documents')
        @include('erp.providers.contacts')
    </div>
</div>