export const notificationState = {
    clients: [],
    clientsLoaded: false,
    clientsLoading: false,
    tags: [],
    tagsLoaded: false,
    tagsLoading: false,
    emailPagination: {page: 1, size: 10, totalPages: 0},
    smsPagination: {page: 1, size: 10, totalPages: 0},
    whatsappPagination: {page: 1, size: 20, totalPages: 0},
    activeChannel: 'email',
    resendEmailId: null,
    resendSmsId: null,
    emailDetail: null,
    emailEditor: null,
    savedEditorRange: null,
    whatsappConversationId: null,
    whatsappConversation: null,
    whatsappTemplates: [],
    whatsappPolling: false,
    whatsappPusherChannel: null,
    whatsappPusherHandler: null,
    whatsappPusherWaiting: false,
};